import React, { useState, useEffect, useCallback } from 'react';
import { motion } from 'framer-motion';
import {
  ArrowLeft, BarChart3, Users, Globe, MonitorSmartphone,
  Smartphone, Monitor, Clock, Download, FileText, MapPin,
  Loader2, RefreshCw, ExternalLink
} from 'lucide-react';
import {
  Chart as ChartJS,
  CategoryScale, LinearScale, PointElement, LineElement,
  BarElement, ArcElement, Title, Tooltip, Legend, Filler,
} from 'chart.js';
import { Line, Doughnut, Bar } from 'react-chartjs-2';
import { jsPDF } from 'jspdf';
import { fetchQRAnalytics } from '../../../api/analytics.api';
import AnimatedPage from '../../../components/ui/AnimatedPage';
import { SkeletonKPI, SkeletonChart } from '../../../components/ui/Skeleton';
import ScanHeatmap from '../../../components/ScanHeatmap';

ChartJS.register(
  CategoryScale, LinearScale, PointElement, LineElement,
  BarElement, ArcElement, Title, Tooltip, Legend, Filler,
);

const PERIODS = [
  { label: '24h', value: '24h' },
  { label: '7 Days', value: '7d' },
  { label: '30 Days', value: '30d' },
  { label: '90 Days', value: '90d' },
];

const QRAnalyticsView = ({ qrId, onBack }) => {
  const [period, setPeriod] = useState('7d');
  const [loading, setLoading] = useState(true);
  const [data, setData] = useState(null);

  const loadData = useCallback(async () => {
    setLoading(true);
    try {
      const result = await fetchQRAnalytics(qrId, period);
      if (result.success) setData(result.data);
    } catch (err) {
      console.error('Failed to load QR analytics:', err);
    } finally {
      setLoading(false);
    }
  }, [qrId, period]);

  useEffect(() => { loadData(); }, [loadData]);

  // ── CSV Export ──
  const exportCSV = () => {
    if (!data) return;
    const rows = [['Date', 'Scans']];
    data.timeseries.forEach(d => rows.push([d.date, d.scans]));
    rows.push([]);
    rows.push(['Country', 'Count']);
    data.countries.forEach(c => rows.push([c.name, c.count]));
    rows.push([]);
    rows.push(['Browser', 'Count']);
    data.browsers.forEach(b => rows.push([b.name, b.count]));
    rows.push([]);
    rows.push(['OS', 'Count']);
    data.os.forEach(o => rows.push([o.name, o.count]));

    const csvContent = rows.map(r => r.join(',')).join('\n');
    const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `${data.qrCode.title.replace(/\s+/g, '-')}-analytics.csv`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  // ── PDF Export ──
  const exportPDF = () => {
    if (!data) return;
    const pdf = new jsPDF();
    const w = pdf.internal.pageSize.getWidth();
    let y = 20;

    pdf.setFontSize(20);
    pdf.text(data.qrCode.title, w / 2, y, { align: 'center' });
    y += 10;
    pdf.setFontSize(10);
    pdf.setTextColor(120);
    pdf.text(`Analytics Report — ${period}`, w / 2, y, { align: 'center' });
    y += 15;

    pdf.setTextColor(0);
    pdf.setFontSize(14);
    pdf.text('Overview', 14, y); y += 8;
    pdf.setFontSize(11);
    pdf.text(`Total Scans: ${data.totalScans}`, 14, y); y += 6;
    pdf.text(`Unique Visitors: ${data.uniqueVisitors}`, 14, y); y += 6;
    pdf.text(`QR Type: ${data.qrCode.qrType}`, 14, y); y += 6;
    pdf.text(`Status: ${data.qrCode.isActive ? 'Active' : 'Paused'}`, 14, y); y += 12;

    pdf.setFontSize(14);
    pdf.text('Top Countries', 14, y); y += 8;
    pdf.setFontSize(11);
    data.countries.slice(0, 10).forEach(c => {
      pdf.text(`${c.name}: ${c.count} scans`, 14, y); y += 6;
    });
    y += 6;

    pdf.setFontSize(14);
    pdf.text('Top Browsers', 14, y); y += 8;
    pdf.setFontSize(11);
    data.browsers.slice(0, 5).forEach(b => {
      pdf.text(`${b.name}: ${b.count}`, 14, y); y += 6;
    });
    y += 6;

    pdf.setFontSize(14);
    pdf.text('Scans by Date', 14, y); y += 8;
    pdf.setFontSize(9);
    data.timeseries.forEach(d => {
      if (y > 270) { pdf.addPage(); y = 20; }
      pdf.text(`${d.date}: ${d.scans} scans`, 14, y); y += 5;
    });

    pdf.setFontSize(8);
    pdf.setTextColor(150);
    pdf.text('Generated by NexusQR', w / 2, 290, { align: 'center' });

    pdf.save(`${data.qrCode.title.replace(/\s+/g, '-')}-analytics.pdf`);
  };

  if (!data && loading) {
    return (
      <AnimatedPage className="flex-1 overflow-y-auto p-6 md:p-8 bg-slate-50 dark:bg-slate-950/50">
        <div className="max-w-6xl mx-auto space-y-6">
          <div className="flex items-center gap-4">
            <button onClick={onBack} className="p-2 rounded-lg text-slate-500 hover:bg-slate-100 dark:hover:bg-slate-800">
              <ArrowLeft className="w-5 h-5" />
            </button>
            <div className="h-8 w-48 bg-slate-200 dark:bg-slate-800 rounded animate-pulse" />
          </div>
          <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
            {[1, 2, 3].map(i => <SkeletonKPI key={i} />)}
          </div>
          <SkeletonChart />
        </div>
      </AnimatedPage>
    );
  }

  if (!data) return null;

  // ── Chart configs ──
  const lineData = {
    labels: data.timeseries.map(d => {
      const date = new Date(d.date);
      return date.toLocaleDateString('en-US', { month: 'short', day: 'numeric' });
    }),
    datasets: [{
      label: 'Scans',
      data: data.timeseries.map(d => d.scans),
      borderColor: '#3b82f6',
      backgroundColor: 'rgba(59, 130, 246, 0.1)',
      borderWidth: 2,
      tension: 0.4,
      fill: true,
      pointRadius: data.timeseries.length > 30 ? 0 : 4,
      pointHoverRadius: 6,
      pointBackgroundColor: '#fff',
      pointBorderColor: '#3b82f6',
    }],
  };

  const lineOpts = {
    responsive: true,
    maintainAspectRatio: false,
    plugins: { legend: { display: false }, tooltip: { backgroundColor: '#0f172a', padding: 12, cornerRadius: 8, displayColors: false } },
    scales: {
      x: { grid: { display: false }, ticks: { color: '#64748b', maxTicksLimit: 7 } },
      y: { grid: { color: 'rgba(148, 163, 184, 0.1)' }, ticks: { color: '#64748b' }, beginAtZero: true },
    },
  };

  const osColors = ['#3b82f6', '#10b981', '#f59e0b', '#ef4444', '#8b5cf6', '#ec4899', '#06b6d4', '#84cc16'];
  const doughnutData = {
    labels: data.os.map(d => d.name),
    datasets: [{
      data: data.os.map(d => d.count),
      backgroundColor: data.os.map((_, i) => osColors[i % osColors.length]),
      borderWidth: 0,
      hoverOffset: 4,
    }],
  };
  const doughnutOpts = {
    responsive: true,
    maintainAspectRatio: false,
    plugins: {
      legend: { position: 'bottom', labels: { color: '#64748b', usePointStyle: true, padding: 16, font: { size: 11 } } },
      tooltip: { backgroundColor: '#0f172a', padding: 12, cornerRadius: 8 },
    },
    cutout: '70%',
  };

  const browserBarData = {
    labels: data.browsers.slice(0, 6).map(b => b.name),
    datasets: [{
      label: 'Scans',
      data: data.browsers.slice(0, 6).map(b => b.count),
      backgroundColor: '#3b82f6',
      borderRadius: 6,
      maxBarThickness: 32,
    }],
  };
  const barOpts = {
    responsive: true,
    maintainAspectRatio: false,
    plugins: { legend: { display: false }, tooltip: { backgroundColor: '#0f172a', padding: 12, cornerRadius: 8 } },
    scales: {
      x: { grid: { display: false }, ticks: { color: '#64748b' } },
      y: { grid: { color: 'rgba(148, 163, 184, 0.1)' }, ticks: { color: '#64748b' }, beginAtZero: true },
    },
  };

  const maxCountry = data.countries.length > 0 ? Math.max(...data.countries.map(c => c.count)) : 1;

  const deviceIcon = (type) => {
    if (type === 'mobile' || type === 'tablet') return <Smartphone className="w-3.5 h-3.5" />;
    return <Monitor className="w-3.5 h-3.5" />;
  };

  const timeAgo = (dateStr) => {
    const diff = Date.now() - new Date(dateStr).getTime();
    const mins = Math.floor(diff / 60000);
    if (mins < 1) return 'Just now';
    if (mins < 60) return `${mins}m ago`;
    const hrs = Math.floor(mins / 60);
    if (hrs < 24) return `${hrs}h ago`;
    return `${Math.floor(hrs / 24)}d ago`;
  };

  return (
    <AnimatedPage className="flex-1 overflow-y-auto p-6 md:p-8 bg-slate-50 dark:bg-slate-950/50">
      <div className="max-w-6xl mx-auto space-y-6">

        {/* Header */}
        <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
          <div className="flex items-center gap-4">
            <button onClick={onBack} className="p-2 -ml-2 rounded-lg text-slate-500 hover:bg-slate-100 dark:hover:bg-slate-800 transition-colors">
              <ArrowLeft className="w-5 h-5" />
            </button>
            <div>
              <h1 className="text-2xl font-bold text-slate-900 dark:text-white">{data.qrCode.title}</h1>
              <div className="flex items-center gap-2 mt-1">
                <span className="px-2 py-0.5 bg-blue-50 dark:bg-blue-900/30 text-blue-600 dark:text-blue-400 text-[11px] font-bold uppercase rounded border border-blue-100 dark:border-blue-800">
                  {data.qrCode.qrType}
                </span>
                <span className={`px-2 py-0.5 text-[11px] font-bold uppercase rounded border ${data.qrCode.isActive ? 'bg-emerald-50 dark:bg-emerald-900/30 text-emerald-600 dark:text-emerald-400 border-emerald-100 dark:border-emerald-800' : 'bg-amber-50 dark:bg-amber-900/30 text-amber-600 dark:text-amber-400 border-amber-100 dark:border-amber-800'}`}>
                  {data.qrCode.isActive ? 'Active' : 'Paused'}
                </span>
              </div>
            </div>
          </div>

          <div className="flex items-center gap-2 flex-wrap">
            <button onClick={loadData} disabled={loading} className="p-2 bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-lg hover:bg-slate-50 dark:hover:bg-slate-800 transition-colors">
              {loading ? <Loader2 className="w-4 h-4 animate-spin" /> : <RefreshCw className="w-4 h-4 text-slate-500" />}
            </button>
            <div className="flex bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-lg overflow-hidden">
              {PERIODS.map(p => (
                <button
                  key={p.value}
                  onClick={() => setPeriod(p.value)}
                  className={`px-3 py-2 text-xs font-medium transition-colors ${period === p.value ? 'bg-blue-600 text-white' : 'text-slate-600 dark:text-slate-400 hover:bg-slate-50 dark:hover:bg-slate-800'}`}
                >
                  {p.label}
                </button>
              ))}
            </div>
            <button onClick={exportCSV} className="flex items-center gap-1.5 px-3 py-2 bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-lg text-xs font-medium text-slate-600 dark:text-slate-400 hover:bg-slate-50 dark:hover:bg-slate-800 transition-colors">
              <Download className="w-3.5 h-3.5" /> CSV
            </button>
            <button onClick={exportPDF} className="flex items-center gap-1.5 px-3 py-2 bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-lg text-xs font-medium text-slate-600 dark:text-slate-400 hover:bg-slate-50 dark:hover:bg-slate-800 transition-colors">
              <FileText className="w-3.5 h-3.5" /> PDF
            </button>
          </div>
        </div>

        {/* KPI Cards */}
        <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
          {[
            { title: 'Total Scans', value: data.totalScans.toLocaleString(), icon: BarChart3, color: 'text-blue-500' },
            { title: 'Unique Visitors', value: data.uniqueVisitors.toLocaleString(), icon: Users, color: 'text-emerald-500' },
            { title: 'All-Time Scans', value: data.qrCode.scanCount.toLocaleString(), icon: Globe, color: 'text-violet-500' },
          ].map((kpi, i) => (
            <motion.div
              key={kpi.title}
              className="p-5 bg-white dark:bg-slate-900/40 border border-slate-200 dark:border-slate-800 rounded-2xl"
              initial={{ opacity: 0, y: 16 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: i * 0.08 }}
            >
              <div className="flex items-center justify-between mb-3">
                <span className="text-xs font-medium text-slate-500 uppercase tracking-wide">{kpi.title}</span>
                <kpi.icon className={`w-4 h-4 ${kpi.color}`} />
              </div>
              <span className="text-3xl font-bold text-slate-900 dark:text-white">{kpi.value}</span>
            </motion.div>
          ))}
        </div>

        {/* Scan Volume Chart */}
        <div className="p-6 bg-white dark:bg-slate-900/40 border border-slate-200 dark:border-slate-800 rounded-2xl">
          <h2 className="text-lg font-semibold text-slate-900 dark:text-white mb-4">Scan Volume</h2>
          <div className="h-[280px]">
            {data.timeseries.some(d => d.scans > 0) ? (
              <Line data={lineData} options={lineOpts} />
            ) : (
              <div className="h-full flex items-center justify-center text-slate-400 text-sm">No scans in this period</div>
            )}
          </div>
        </div>

        {/* Devices + Browsers + Geo */}
        <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">

          {/* OS Breakdown */}
          <div className="p-6 bg-white dark:bg-slate-900/40 border border-slate-200 dark:border-slate-800 rounded-2xl">
            <div className="flex items-center gap-2 mb-4">
              <MonitorSmartphone className="w-4 h-4 text-slate-400" />
              <h2 className="text-lg font-semibold text-slate-900 dark:text-white">Operating Systems</h2>
            </div>
            <div className="h-[220px] flex items-center justify-center">
              {data.os.length > 0 ? (
                <Doughnut data={doughnutData} options={doughnutOpts} />
              ) : (
                <span className="text-sm text-slate-400">No device data</span>
              )}
            </div>
          </div>

          {/* Browser Breakdown */}
          <div className="p-6 bg-white dark:bg-slate-900/40 border border-slate-200 dark:border-slate-800 rounded-2xl">
            <div className="flex items-center gap-2 mb-4">
              <Globe className="w-4 h-4 text-slate-400" />
              <h2 className="text-lg font-semibold text-slate-900 dark:text-white">Browsers</h2>
            </div>
            <div className="h-[220px]">
              {data.browsers.length > 0 ? (
                <Bar data={browserBarData} options={barOpts} />
              ) : (
                <div className="h-full flex items-center justify-center text-sm text-slate-400">No browser data</div>
              )}
            </div>
          </div>

          {/* Top Countries */}
          <div className="p-6 bg-white dark:bg-slate-900/40 border border-slate-200 dark:border-slate-800 rounded-2xl">
            <div className="flex items-center gap-2 mb-4">
              <MapPin className="w-4 h-4 text-slate-400" />
              <h2 className="text-lg font-semibold text-slate-900 dark:text-white">Top Countries</h2>
            </div>
            <div className="space-y-3">
              {data.countries.length > 0 ? data.countries.map((c, i) => (
                <div key={i} className="flex items-center justify-between">
                  <span className="text-sm font-medium text-slate-700 dark:text-slate-300">{c.name}</span>
                  <div className="flex items-center gap-3">
                    <span className="text-xs text-slate-500">{c.count}</span>
                    <div className="w-20 h-1.5 bg-slate-100 dark:bg-slate-800 rounded-full overflow-hidden">
                      <div className="h-full bg-blue-500 rounded-full" style={{ width: `${(c.count / maxCountry) * 100}%` }} />
                    </div>
                  </div>
                </div>
              )) : (
                <div className="text-sm text-slate-400 text-center py-6">No geo data</div>
              )}
            </div>
          </div>
        </div>

        {/* Top Cities + Recent Scans */}
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">

          {/* Top Cities */}
          <div className="p-6 bg-white dark:bg-slate-900/40 border border-slate-200 dark:border-slate-800 rounded-2xl">
            <h2 className="text-lg font-semibold text-slate-900 dark:text-white mb-4">Top Cities</h2>
            <div className="space-y-3">
              {data.cities.length > 0 ? data.cities.map((c, i) => (
                <div key={i} className="flex items-center justify-between">
                  <span className="text-sm text-slate-700 dark:text-slate-300">
                    {c.city !== 'Unknown' ? `${c.city}, ` : ''}{c.country}
                  </span>
                  <span className="text-xs font-medium text-slate-500">{c.count} scans</span>
                </div>
              )) : (
                <div className="text-sm text-slate-400 text-center py-6">No city data</div>
              )}
            </div>
          </div>

          {/* Recent Scans */}
          <div className="p-6 bg-white dark:bg-slate-900/40 border border-slate-200 dark:border-slate-800 rounded-2xl">
            <h2 className="text-lg font-semibold text-slate-900 dark:text-white mb-4">Recent Scans</h2>
            <div className="space-y-2 max-h-[320px] overflow-y-auto">
              {data.recentScans.length > 0 ? data.recentScans.map((scan, i) => (
                <div key={scan.id || i} className="flex items-center gap-3 p-2.5 rounded-lg hover:bg-slate-50 dark:hover:bg-slate-800/50 transition-colors">
                  <div className="p-1.5 bg-slate-100 dark:bg-slate-800 rounded-lg text-slate-500">
                    {deviceIcon(scan.deviceType)}
                  </div>
                  <div className="flex-1 min-w-0">
                    <p className="text-xs text-slate-700 dark:text-slate-300">
                      {scan.city && scan.city !== 'Unknown' ? `${scan.city}, ` : ''}{scan.country || 'Unknown'}
                    </p>
                    <p className="text-[11px] text-slate-400">{scan.os || 'Unknown'} &middot; {scan.browser || 'Unknown'}</p>
                  </div>
                  <span className="text-[11px] text-slate-400 whitespace-nowrap">{timeAgo(scan.scannedAt)}</span>
                </div>
              )) : (
                <div className="text-sm text-slate-400 text-center py-6">No scans yet</div>
              )}
            </div>
          </div>
        </div>

        {/* Scan Heatmap for this QR */}
        <ScanHeatmap qrId={qrId} />

      </div>
    </AnimatedPage>
  );
};

export default QRAnalyticsView;
